In [1]:
import numpy as np

## 1. MAE 와 RMSE 함수 구현하기
- 다음과 같이 실제 값과 , 모델이 예측한 값이 각각 100개가 있다.
- 실제값과 예측값 사이에 평균 오차를 구하는 함수 두개를 구현해보자.

In [2]:
np.random.seed(42)
target = np.random.randint(50, 91,100) # 정답값
pred = np.random.randint(40, 100,100) # 예측값
target , pred, len(target),len(pred)

(array([88, 78, 64, 57, 70, 88, 68, 72, 60, 60, 73, 85, 89, 73, 52, 71, 51,
        73, 79, 87, 51, 70, 82, 61, 71, 74, 76, 77, 65, 64, 52, 86, 56, 70,
        58, 88, 67, 53, 74, 63, 58, 75, 51, 69, 77, 56, 57, 84, 63, 66, 85,
        89, 53, 51, 55, 53, 78, 67, 75, 83, 59, 85, 63, 80, 64, 57, 63, 72,
        89, 70, 65, 67, 73, 75, 74, 90, 78, 64, 50, 74, 56, 58, 73, 50, 57,
        73, 60, 66, 57, 84, 84, 82, 54, 88, 90, 77, 56, 58, 57, 61]),
 array([73, 72, 87, 94, 62, 63, 76, 74, 83, 79, 61, 66, 74, 40, 74, 76, 86,
        53, 42, 40, 44, 65, 94, 53, 78, 66, 48, 54, 54, 65, 81, 99, 52, 90,
        71, 78, 88, 91, 71, 43, 69, 76, 62, 78, 84, 54, 82, 68, 75, 52, 71,
        46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83, 59, 69,
        50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42, 78, 45,
        47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71, 63]),
 100,
 100)

### MAE(Mean Absolute Error)
- 실제 값과 예측 값의 차이를 절대값으로 변환해 평균화
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [3]:
def mae(target,pred):
    return np.mean(np.abs(target- pred))
mae(target,pred)

17.8

### RMSE(Root Mean Squared Error)
- 실제 값과 예측 값의 차이를 제곱한 뒤 평균화한 후에 루트

$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [9]:
def rmse(target,pred):
    return np.mean(np.square(target - pred)) ** 0.5
rmse(target,pred)

21.829796151132516

## 2.시그모이드 함수 구현하기
- S와 같은 형태로 미분 가능한 0~1 사이의 값을 반환한다.
- 이진 분류에 출력 함수로 사용된다.
$$
y = \frac{1}{1+e^{-x}}
$$

- x 변수에 있는 배열의 요소들을 시그모이드 함수에 넣어 0 ~ 1 사이 값들로 변경하시오.

In [10]:
np.random.seed(42)
x = np.random.randint(-10,10,10)
x

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7])

```
아래 셀의 코드 작성하여 함수구현
```

In [11]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
sigmoid(x)

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

## 3.다음의 3행 2열형태의 배열에서 두개 열 위치를 바꾸시오.

In [13]:
np.random.seed(42)
arr = np.random.randint(50,100,[3,2])
arr

array([[88, 78],
       [64, 92],
       [57, 70]])

```
아래 셀의 코드 작성
```

In [14]:
arr[:,[1,0]]

array([[78, 88],
       [92, 64],
       [70, 57]])

In [15]:
arr[:,::-1]

array([[78, 88],
       [92, 64],
       [70, 57]])

## 4.다음의 배열에서 각행의 평균을 구하시오.

In [16]:
np.random.seed(42)
arr = np.random.randint(50, 101, (4, 3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]])

```
아래 셀의 코드 작성
```

In [27]:
arr.mean(axis=1)

array([76.66666667, 73.        , 76.        , 64.33333333])

## 데이터 설명
- 다음은 2021년 삼성주식 데이터이다
- 시계열 학습이 가능한 형태로 변환되어있다.
- 행마다 10일치의 시작가 ,상한가 , 하한가, 종가 에 대한 행렬이 들어가 있다.

In [17]:
# from google.colab import drive
# drive.mount("/content/drive/")

# DATA_PATH = "/content/drive/MyDrive/data/"

# samsung_stock_3d = np.load(f"{DATA_PATH}samsung_stock_2021_3d.npy")
# samsung_stock_3d.shape

samsung_stock_3d=np.load("data/samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

#10일치의 234개의 데이터

(234, 10, 4)

- 한행을 보면 2차원 행렬 형태로 되어있다.
    - 행은 일자
    - 열은 시작가,상한가,하한가,종가 순

In [18]:
samsung_stock_3d[0]

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000]], dtype=int64)

## 머신러닝 모델에서 학습이 가능하게 2차원 형태로 변경해보자..


## 5. samsung_stock_3d 변수의 3차원 데이터에 각 행의 행렬을 벡터 형태로 변환하여 데이터셋을 2차원형태로 변경하여 samsung_stock_2d 라는 변수에 담으세요.
- samsung_stock_2d 의 shape -> (234,40)

```
아래 셀의 코드 작성
```

In [19]:
samsung_stock_2d = samsung_stock_3d.reshape(samsung_stock_3d.shape[0], -1) #샘플차원만을 남김
samsung_stock_2d.shape,samsung_stock_2d

((234, 40),
 array([[81000, 84400, 80200, ..., 91800, 88000, 88000],
        [81600, 83900, 81600, ..., 87300, 84100, 85000],
        [83300, 84500, 82100, ..., 88000, 83600, 87000],
        ...,
        [78300, 78600, 77100, ..., 78300, 77500, 78100],
        [77400, 78200, 77000, ..., 79400, 78800, 79400],
        [77400, 77600, 76800, ..., 80000, 79300, 79900]], dtype=int64))

## 6. samsung_stock_3d 변수의 3차원 데이터에 각 행의 시작가 ,상한가 , 하한가, 종가별로 평균을 구해 2차원 형태로 변경하여 samsung_stock_avg 라는 변수에 담으세요.
- samsung_stock_avg 의 shape -> (234,4)

```
아래 셀의 코드 작성
```

In [20]:
samsung_stock_avg = samsung_stock_3d.mean(axis=1)
samsung_stock_avg.shape

(234, 4)

## 7. 5번과 6번에서 생성한 변수들의 데이터를 옆으로 합쳐서 x_train 변수에 넣어주세요.

```
아래 셀의 코드 작성
```

In [21]:
x_train = np.concatenate([samsung_stock_2d, samsung_stock_avg], axis=1)
x_train.shape

(234, 44)

## 8. x_train변수의 각 특성(열)들에 최대값과 최소값들을 구하시오.

```
아래 셀의 코드 작성
```

In [22]:
mins, maxs = np.quantile(x_train,[0,1],axis=0)

In [23]:
mins.shape, maxs.shape

((44,), (44,))

## 9.x_train변수의 각 특성(열)들에 분위수기준으로 5% 지점값들과 95% 지점값들을 구하시오

```
아래 셀의 코드 작성
```

In [24]:
mins, maxs = np.quantile(x_train,[0.05,0.95],axis=0)

In [25]:
mins.shape, maxs.shape

((44,), (44,))

## 10. 이상치를 제거해보기
- x_train변수의 특성(열)들에 분위수 기준 5% 지점의 미만값들을 5% 지점값으로 변경하고
- 95% 지점을 초과하는 값들을 95% 지점값으로 변경해보세요.

```
아래 셀의 코드 작성
```

In [26]:
np.clip(x_train,mins, maxs)

array([[81000. , 84400. , 80200. , ..., 87506. , 84803.5, 85781. ],
       [81600. , 83900. , 81600. , ..., 87506. , 84803.5, 85781. ],
       [83300. , 84500. , 82100. , ..., 87506. , 84803.5, 85781. ],
       ...,
       [78300. , 78600. , 77100. , ..., 78010. , 76840. , 77490. ],
       [77400. , 78200. , 77000. , ..., 78090. , 77010. , 77690. ],
       [77400. , 77600. , 76800. , ..., 78270. , 77240. , 77860. ]])

## 11.x_train 데이터셋에서 20%의 데이터의 인덱스들을 리스트에 담아 5번 랜덤하게 반환하는 제너레이터(리스트 형태로 반환 가능) 함수를 만들어주세요
- 단, 5번 랜덤하게 반환하는 과정에서 동일한 행의 인덱스가 나오면 안된다.
    - 한번 나온 행의 인덱스는 다시 나오면 안된다는 의미
    - 모든 행의 인덱스가 한번씩은 무조건 나와야한다.
- 234행 나누기 5를 할경우 나머지가 생기기 때문에 5번째 나오는 인덱스들이 담긴 리스트는 앞서 나온 크기와 차이가 나도 된다.  
- 제너레이터가 어려우신 분들은 그냥 인덱스들을 담고 있는 리스트들을 새로운 리스트에 담아서 return 하셔도 됩니다.

```
아래 셀의 코드 작성하여 함수 구현
```

In [38]:
def split_dataset(dataset):
    n_split = 5
    n_row = dataset.shape[0] # 총 샘플수
    index_arr = np.arange(n_row) # 인덱스 배열
    np.random.shuffle(index_arr) # 무작위를 위해 섞기
    n_samples = n_row // n_split # 반복별 샘플수

    result = []
    for i in range(n_split):
        start = i * n_samples
        end = start + n_samples
        if i+1 == n_split: # 마지막 반복 이라면?
            end = n_row
        result.append(index_arr[start:end])
    return result

In [34]:
def split_dataset(dataset):
    n_split = 5
    n_row = dataset.shape[0] # 총 샘플수
    index_arr = np.arange(n_row) # 인덱스 배열
    np.random.shuffle(index_arr) # 무작위를 위해 섞기
    n_samples = n_row // n_split # 반복별 샘플수

    for i in range(n_split):
        start = i * n_samples
        end = start + n_samples
        print(i,start,end,n_row)

        if i+1 == n_split: # 마지막 반복 이라면?
            end = n_row
            print(n_row)
        yield index_arr[start:end]

In [40]:
def split_dataset(dataset):
    n_split = 5
    n_row = dataset.shape[0] # 총 샘플수
    index_arr = np.arange(n_row) # 인덱스 배열
    np.random.shuffle(index_arr) # 무작위를 위해 섞기
    n_samples = n_row // n_split # 반복별 샘플수
    n_sub = n_row -  n_samples * n_split # 나머지 개수
    index_list = index_arr[:n_row-n_sub].reshape(n_split,-1).tolist()

    if n_sub > 0: # 나머지 개수가 있다면?
        index_list[-1].extend( index_arr[n_row-n_sub:].tolist() )
    yield from index_list

- 다음 셀은 위에 함수 실행 결과를 검증하는 부분

In [35]:
index_list = split_dataset(x_train)
lst = [] # 크기가 데이터셋 크기와 같은지 확인하기 위한 리스트
for idx in index_list:
    idx = list(set(idx)) # 중복 인덱스가 있으면 안되기 때문에 제거하기 위한 코드
    lst.extend(idx) # 리스트에 담기

lst = list(set(lst)) # 모든 인덱스들 안에 중복 인덱스가 있으면 안되기 때문에 중복 제거하기 위한 코드

# 크기가 데이터셋 크기와 같고(즉 234개면 성공), 인덱스 최대값이 233 이고, 최소값이 0 이면 성공!!

print(f"리스트 크기: {len(lst)}")
print(f"최대값: {max(lst)}")
print(f"최소값: {min(lst)}")

0 0 46 234
1 46 92 234
2 92 138 234
3 138 184 234
4 184 230 234
234
리스트 크기: 234
최대값: 233
최소값: 0


In [44]:
a=[1,2,3]
a.append([1,2,3]),a.extend([1,2,3])
a

[1, 2, 3, [1, 2, 3], 1, 2, 3]

## 12.시계열 학습데이터 만들기
- 다음의 데이터는 2021년도 삼성 주식 데이터이다.
- 열부분은 시작가 ,상한가 , 하한가, 종가 순으로 되어있다.
- 행은 2021년도 거래 일자이다.

In [45]:
import os
DATA_PATH=os.getcwd()
DATA_PATH=DATA_PATH.replace("\\",'/')

In [47]:
import os

DATA_PATH = "C:/study/01_numpy&pandas/data"
file_path = os.path.join(DATA_PATH, "samsung_stock_2021.npy")

# 파일 로드
samsung_stock = np.load(file_path)

In [51]:
samsung_stock,samsung_stock.shape

(array([[81000, 84400, 80200, 83000],
        [81600, 83900, 81600, 83900],
        [83300, 84500, 82100, 82200],
        [82800, 84200, 82700, 82900],
        [83300, 90000, 83000, 88800],
        [90000, 96800, 89500, 91000],
        [90300, 91400, 87800, 90600],
        [89800, 91200, 89100, 89700],
        [88700, 90000, 88700, 89700],
        [89800, 91800, 88000, 88000],
        [86600, 87300, 84100, 85000],
        [84500, 88000, 83600, 87000],
        [89000, 89000, 86500, 87200],
        [87500, 88600, 86500, 88100],
        [89000, 89700, 86800, 86800],
        [87000, 89900, 86300, 89400],
        [88800, 89200, 86500, 86700],
        [86600, 87700, 85600, 85600],
        [83200, 85600, 83200, 83700],
        [84500, 85000, 82000, 82000],
        [81700, 83400, 81000, 83000],
        [84100, 86400, 83700, 84400],
        [84800, 85400, 83400, 84600],
        [83500, 83800, 82100, 82500],
        [83100, 84000, 82500, 83500],
        [83800, 84200, 83000, 83000],
        [840

In [49]:
samsung_stock[-5:] # 뒤에 5행만 확인해보자

array([[80200, 80800, 80200, 80500],
       [80600, 80600, 79800, 80200],
       [80200, 80400, 79700, 80300],
       [80200, 80200, 78500, 78800],
       [78900, 79500, 78100, 78300]], dtype=int64)

### 시계열 학습데이터 형태로 반환하는 함수를 만드시오.
- samsung_stock 변수의 데이터는 2차원 데이터이다.
- 학습데이터는 행별로 10일치의 행과 4열(시작가 ,상한가 , 하한가, 종가) 형태의 행렬을 담고 있는 3차원 형태의 데이터셋으로 변경하시오.
- 정답데이터는 미래의 5일치의 종가를 예측해야 한다는 가정하에 행별로 미래의 5일치의 종가가 담긴 2차원 형태의 데이터셋으로 변경하시오.
- 1일씩 이동하면서 데이터셋을 구성하시오.

In [52]:
samsung_stock_3d.shape

(234, 10, 4)

```
아래 셀의 코드 작성하여 함수 구현
```

In [55]:
samsung_stock.shape[0] + 1

249

In [64]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    x_train = []
    y_train = []

    for i in range(seq_len, samsung_stock.shape[0] + 1 - pred_len):
        x = samsung_stock[i-seq_len : i]
        x_train.append(x)
        y = samsung_stock[i:i+pred_len, 3]
        y_train.append(y)

    x_train = np.array(x_train)
    y_train = np.array(y_train)

    return x_train, y_train

In [41]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    window_size = seq_len + pred_len

    window_arr = [
        samsung_stock[i-window_size : i]
        for i in range(window_size, samsung_stock.shape[0] + 1)
    ]

    window_arr = np.array(window_arr)
    x_train = window_arr[:,:seq_len]
    y_train = window_arr[:,seq_len:,3]

    return x_train, y_train

- 다음 셀들은 위에 함수 실행 결과를 검증하는 부분

In [65]:
x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

((234, 10, 4), (234, 5))

In [66]:
import os 

os.chdir('C:\\study\\01_numpy&pandas\\data')
np.save('y_train.npy',arr=y_train)

In [67]:
DATA_PATH=os.getcwd()

x_samsung_stock = np.load(f"{DATA_PATH}\\samsung_stock_2021_3d.npy")
y_samsung_stock = np.load(f"{DATA_PATH}\\y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!

(True, True)

In [69]:
x_train

array([[[81000, 84400, 80200, 83000],
        [81600, 83900, 81600, 83900],
        [83300, 84500, 82100, 82200],
        ...,
        [89800, 91200, 89100, 89700],
        [88700, 90000, 88700, 89700],
        [89800, 91800, 88000, 88000]],

       [[81600, 83900, 81600, 83900],
        [83300, 84500, 82100, 82200],
        [82800, 84200, 82700, 82900],
        ...,
        [88700, 90000, 88700, 89700],
        [89800, 91800, 88000, 88000],
        [86600, 87300, 84100, 85000]],

       [[83300, 84500, 82100, 82200],
        [82800, 84200, 82700, 82900],
        [83300, 90000, 83000, 88800],
        ...,
        [89800, 91800, 88000, 88000],
        [86600, 87300, 84100, 85000],
        [84500, 88000, 83600, 87000]],

       ...,

       [[78300, 78600, 77100, 77400],
        [77400, 78200, 77000, 78200],
        [77400, 77600, 76800, 76900],
        ...,
        [76800, 78000, 76800, 78000],
        [77600, 77800, 76800, 77100],
        [77900, 78300, 77500, 78100]],

       [[77400,

In [70]:
y_train

array([[85000, 87000, 87200, 88100, 86800],
       [87000, 87200, 88100, 86800, 89400],
       [87200, 88100, 86800, 89400, 86700],
       ...,
       [79400, 79900, 80500, 80200, 80300],
       [79900, 80500, 80200, 80300, 78800],
       [80500, 80200, 80300, 78800, 78300]], dtype=int64)